### ISSUE TITLE
Register counter not increasing

### ISSUE THREAD

**Issue by wied03** [wied03/ansible-ruby#30]
With each task, the variable should be unique. Currently;

```ruby
play 'block fun' do
  local_host

  block do
    task 'say hello' do
      result = command 'uname'

      failed_when "'Linux' not in #{result.stdout}"
    end

    task 'and goodbye' do
      result = command 'uname -a'

      failed_when "'Darwin' not in #{result.stdout}"
    end

    ansible_when jinja('stuff')
  end
end
```
is compiling to:
```yml
---
# This is a generated YAML file by ansible-ruby, DO NOT EDIT
- hosts: localhost
  name: block fun
  connection: local
  tasks:
  - block:
    - name: say hello
      command: uname
      register: result_1
      failed_when: "'Darwin' not in result_1.stdout"
    - name: and goodbye
      command: uname -a
      register: result_1
      failed_when: "'Darwin' in result_1.stdout"
    when: "{{ stuff }}"
```
